version: "3.9"
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  web:
    container_name: test_docker
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code2
    ports:
      - "8000:8000"
    depends_on:
      - redis